spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2_db
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: debug
